// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: files.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countFiles = `-- name: CountFiles :one
SELECT COUNT(*) FROM files
`

func (q *Queries) CountFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilesByUserID = `-- name: CountFilesByUserID :one
SELECT COUNT(*) FROM files
WHERE user_id = $1
`

func (q *Queries) CountFilesByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (user_id, filename, original_name, mime_type, size, storage_driver, storage_path, url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, filename, original_name, mime_type, size, storage_driver, storage_path, url, created_at, updated_at
`

type CreateFileParams struct {
	UserID        uuid.UUID `json:"user_id" db:"user_id"`
	Filename      string    `json:"filename" db:"filename"`
	OriginalName  string    `json:"original_name" db:"original_name"`
	MimeType      string    `json:"mime_type" db:"mime_type"`
	Size          int64     `json:"size" db:"size"`
	StorageDriver string    `json:"storage_driver" db:"storage_driver"`
	StoragePath   string    `json:"storage_path" db:"storage_path"`
	URL           *string   `json:"url" db:"url"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.UserID,
		arg.Filename,
		arg.OriginalName,
		arg.MimeType,
		arg.Size,
		arg.StorageDriver,
		arg.StoragePath,
		arg.URL,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.Size,
		&i.StorageDriver,
		&i.StoragePath,
		&i.URL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteFilesByUserID = `-- name: DeleteFilesByUserID :exec
DELETE FROM files
WHERE user_id = $1
`

func (q *Queries) DeleteFilesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFilesByUserID, userID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, filename, original_name, mime_type, size, storage_driver, storage_path, url, created_at, updated_at FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.Size,
		&i.StorageDriver,
		&i.StoragePath,
		&i.URL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, user_id, filename, original_name, mime_type, size, storage_driver, storage_path, url, created_at, updated_at FROM files
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListFilesParams struct {
	Limit  int32 `json:"limit" db:"limit"`
	Offset int32 `json:"offset" db:"offset"`
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.Size,
			&i.StorageDriver,
			&i.StoragePath,
			&i.URL,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByUserID = `-- name: ListFilesByUserID :many
SELECT id, user_id, filename, original_name, mime_type, size, storage_driver, storage_path, url, created_at, updated_at FROM files
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFilesByUserIDParams struct {
	UserID uuid.UUID `json:"user_id" db:"user_id"`
	Limit  int32     `json:"limit" db:"limit"`
	Offset int32     `json:"offset" db:"offset"`
}

func (q *Queries) ListFilesByUserID(ctx context.Context, arg ListFilesByUserIDParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.Size,
			&i.StorageDriver,
			&i.StoragePath,
			&i.URL,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type FileQuerier interface {
	CountFiles(ctx context.Context) (int64, error)
	CountFilesByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	DeleteFile(ctx context.Context, id uuid.UUID) error
	DeleteFilesByUserID(ctx context.Context, userID uuid.UUID) error
	GetFileByID(ctx context.Context, id uuid.UUID) (File, error)
	ListFiles(ctx context.Context, arg ListFilesParams) ([]File, error)
	ListFilesByUserID(ctx context.Context, arg ListFilesByUserIDParams) ([]File, error)
}

var _ FileQuerier = (*Queries)(nil)
