// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID `json:"id" db:"id"`
	Email        string    `json:"email" db:"email"`
	PasswordHash string    `json:"password_hash" db:"password_hash"`
	Name         string    `json:"name" db:"name"`
	Role         string    `json:"role" db:"role"`
	CreatedAt    time.Time `json:"created_at" db:"created_at"`
	UpdatedAt    time.Time `json:"updated_at" db:"updated_at"`
}

type File struct {
	ID            uuid.UUID `json:"id" db:"id"`
	UserID        uuid.UUID `json:"user_id" db:"user_id"`
	Filename      string    `json:"filename" db:"filename"`
	OriginalName  string    `json:"original_name" db:"original_name"`
	MimeType      string    `json:"mime_type" db:"mime_type"`
	Size          int64     `json:"size" db:"size"`
	StorageDriver string    `json:"storage_driver" db:"storage_driver"`
	StoragePath   string    `json:"storage_path" db:"storage_path"`
	URL           *string   `json:"url" db:"url"`
	CreatedAt     time.Time `json:"created_at" db:"created_at"`
	UpdatedAt     time.Time `json:"updated_at" db:"updated_at"`
}
